import chalk from 'chalk';
import { promises as fs } from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export class PrePushHookCommand {
    constructor(options = {}) {
        this.projectPath = options.projectPath || process.cwd();
        this.hookPath = path.join(this.projectPath, '.git', 'hooks', 'pre-push');
        this.auditPath = path.join(this.projectPath, '.sentinel', 'hook-audit.log');
    }

    async run(args) {
        const action = args[0] || 'install';
        
        switch (action) {
            case 'install':
                return this.installHook();
            case 'uninstall':
                return this.uninstallHook();
            case 'status':
                return this.checkStatus();
            case 'test':
                return this.testHook();
            default:
                this.showHelp();
        }
    }

    showHelp() {
        console.log(chalk.cyan('\n  Sentinel Pre-Push Hook\n'));
        console.log(chalk.gray('  Commands:'));
        console.log(chalk.gray('    install   - Install pre-push hook'));
        console.log(chalk.gray('    uninstall - Remove pre-push hook'));
        console.log(chalk.gray('    status    - Check hook status'));
        console.log(chalk.gray('    test      - Test the hook\n'));
        console.log(chalk.gray('  Environment:'));
        console.log(chalk.gray('    SENTINEL_SKIP=1 git push - Bypass the hook (logged)\n'));
    }

    async installHook() {
        console.log(chalk.cyan('\n  Installing Pre-Push Hook\n'));

        const hookContent = `#!/bin/sh
# Sentinel Pre-Push Hook
# Generated by Sentinel CLI

# Check for bypass
if [ "$SENTINEL_SKIP" = "1" ]; then
    echo "⚠️  Sentinel hook bypassed"
    DATE=$(date '+%Y-%m-%d %H:%M:%S')
    USER=$(whoami)
    BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "unknown")
    echo "[$DATE] Bypassed by $USER on branch $BRANCH" >> "\${SENTINEL_AUDIT_LOG:-.sentinel/hook-audit.log}"
    exit 0
fi

# Check if pushing to protected branch
PROTECTED_BRANCHES="main master develop production staging"
CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || echo "")

for branch in $PROTECTED_BRANCHES; do
    if [ "$CURRENT_BRANCH" = "$branch" ]; then
        echo "🛡️  Running Sentinel security check for $branch..."
        node "\${SENTINEL_PATH:-$(dirname $0)/../../src/core/cli.js}" ci --fail-on critical
        RESULT=$?
        if [ $RESULT -ne 0 ]; then
            echo "❌ Push blocked by Sentinel - critical issues found"
            exit 1
        fi
        break
    fi
done

exit 0
`;

        try {
            await fs.mkdir(path.dirname(this.hookPath), { recursive: true });
        } catch (e) {}

        await fs.writeFile(this.hookPath, hookContent, 'utf8');
        
        try {
            await execAsync(`chmod +x "${this.hookPath}"`);
        } catch (e) {}

        console.log(chalk.green('  ✓ Pre-push hook installed'));
        console.log(chalk.gray('\n  Protected branches: main, master, develop, production, staging'));
        console.log(chalk.gray('  Run "SENTINEL_SKIP=1 git push" to bypass (logged)\n'));
    }

    async uninstallHook() {
        try {
            await fs.unlink(this.hookPath);
            console.log(chalk.green('  ✓ Pre-push hook removed'));
        } catch (e) {
            console.log(chalk.yellow('  No pre-push hook found'));
        }
    }

    async checkStatus() {
        console.log(chalk.cyan('\n  Pre-Push Hook Status\n'));

        try {
            await fs.access(this.hookPath);
            
            const content = await fs.readFile(this.hookPath, 'utf8');
            
            if (content.includes('Sentinel')) {
                console.log(chalk.green('  ✓ Hook installed'));
                console.log(chalk.gray('\n  Protected branches:'));
                console.log(chalk.gray('    - main, master'));
                console.log(chalk.gray('    - develop, staging'));
                console.log(chalk.gray('    - production'));
            } else {
                console.log(chalk.yellow('  ⚠️  Hook exists but may not be Sentinel'));
            }
        } catch (e) {
            console.log(chalk.yellow('  ✗ Hook not installed'));
            console.log(chalk.gray('\n  Run "sentinel pre-push install"\n'));
        }

        try {
            const auditContent = await fs.readFile(this.auditPath, 'utf8');
            const lines = auditContent.split('\n').filter(Boolean);
            
            if (lines.length > 0) {
                console.log(chalk.gray('\n  Recent bypasses:'));
                for (const line of lines.slice(-5)) {
                    console.log(chalk.yellow('    ' + line));
                }
            }
        } catch (e) {}
    }

    async testHook() {
        console.log(chalk.gray('\n  Testing Sentinel pre-push...\n'));

        try {
            const { stdout } = await execAsync('node src/core/cli.js analyze --format json', {
                cwd: this.projectPath,
                maxBuffer: 10 * 1024 * 1024
            });

            const result = JSON.parse(stdout);
            const issues = result.issues || [];
            const critical = issues.filter(i => i.severity === 'critical').length;

            if (critical > 0) {
                console.log(chalk.red(`  ❌ Test failed - ${critical} critical issue(s) found`));
                return { success: false, critical };
            }

            console.log(chalk.green('  ✓ Test passed - no critical issues'));
            return { success: true, critical: 0 };

        } catch (e) {
            console.log(chalk.yellow(`  ⚠️  Test warning: ${e.message}`));
            return { success: true, warning: e.message };
        }
    }
}

export async function runPrePushCommand(args, options = {}) {
    const command = new PrePushHookCommand(options);
    return command.run(args);
}

export default { PrePushHookCommand, runPrePushCommand };
