import { promises as fs } from 'fs';
import { join } from 'path';

const TEST_FILE_PATTERNS = [
  /__tests?__/,
  /\.test\./,
  /\.spec\./,
  /\/test\//,
  /\/tests\//,
  /\/spec\//,
  /\-test\./,
  /test_/,
  /_test\./,
];

const MOCK_FILE_PATTERNS = [
  /__mocks?__/,
  /\/mock(s)?\//,
  /\.mock\./,
  /mock_/,
  /_mock\./,
];

const GENERATED_FILE_PATTERNS = [
  /\.min\./,
  /\.bundle\./,
  /\.compiled\./,
  /\.generated\./,
  /\/dist\//,
  /\/build\//,
  /node_modules/,
  /\.g\.js$/,
  /\.g\.ts$/,
  /generated/,
  /autogenerated/,
];

const FRAMEWORK_PATTERNS = {
  react: [
    /react/i,
    /use[A-Z]/,
    /useState/,
    /useEffect/,
    /createElement/,
  ],
  vue: [
    /vue/i,
    /vuex/,
    /pinia/,
    /ref\(/,
    /computed\(/,
  ],
  angular: [
    /@Component/,
    /@Injectable/,
    /@NgModule/,
    /NgOnInit/,
  ],
  nextjs: [
    /getServerSideProps/,
    /getStaticProps/,
    /getStaticPaths/,
    /next\//,
  ],
  jest: [
    /describe\(/,
    /it\(/,
    /test\(/,
    /expect\(/,
    /beforeEach/,
    /afterEach/,
    /mock\(/,
  ],
  mocha: [
    /describe\(/,
    /it\(/,
    /before\(/,
    /after\(/,
  ],
};

export class ContextAwareSuppression {
  constructor(options = {}) {
    this.enableLearning = options.enableLearning ?? true;
    this.suppressionsFile = options.suppressionsFile || '.sentinel-suppressions.json';
    this.teamSuppressions = new Map();
    this.fileContextCache = new Map();
  }

  async loadTeamSuppressions(projectPath) {
    try {
      const suppressionsPath = join(projectPath, this.suppressionsFile);
      const content = await fs.readFile(suppressionsPath, 'utf-8');
      const data = JSON.parse(content);
      
      this.teamSuppressions = new Map(
        (data.suppressions || []).map(s => [
          `${s.file}:${s.line}:${s.ruleId}`,
          { ...s, teamAcknowledged: true }
        ])
      );
      
      return {
        loaded: true,
        count: this.teamSuppressions.size,
        source: suppressionsPath
      };
    } catch (error) {
      return { loaded: false, count: 0, source: null };
    }
  }

  analyzeFileContext(filePath, content) {
    const fileName = filePath.split(/[/\\]/).pop();
    const directory = filePath.substring(0, filePath.length - fileName.length);
    
    const context = {
      filePath,
      fileName,
      directory,
      isTestFile: this.matchesAnyPattern(filePath, TEST_FILE_PATTERNS),
      isMockFile: this.matchesAnyPattern(filePath, MOCK_FILE_PATTERNS),
      isGeneratedFile: this.matchesAnyPattern(filePath, GENERATED_FILE_PATTERNS),
      frameworks: this.detectFrameworks(content),
      isExampleCode: this.isExampleCode(filePath, content),
      isDocumentation: this.isDocumentation(filePath),
    };

    context.isLikelyFalsePositive = (
      context.isTestFile ||
      context.isMockFile ||
      context.isGeneratedFile ||
      context.isExampleCode
    );

    return context;
  }

  matchesAnyPattern(str, patterns) {
    return patterns.some(pattern => pattern.test(str));
  }

  detectFrameworks(content) {
    const detected = [];
    
    for (const [framework, patterns] of Object.entries(FRAMEWORK_PATTERNS)) {
      const matches = patterns.filter(pattern => pattern.test(content));
      if (matches.length >= 2) {
        detected.push(framework);
      }
    }
    
    return detected;
  }

  isExampleCode(filePath, content) {
    const exampleIndicators = [
      /example/i,
      /demo/i,
      /sample/i,
      /template/i,
      /boilerplate/i,
      /scaffold/i,
      /tutorial/i,
    ];
    
    const hasExampleIndicator = exampleIndicators.some(p => 
      p.test(filePath) || p.test(content.substring(0, 500))
    );
    
    if (hasExampleIndicator) return true;
    
    const commentPatterns = [
      /\/\/\s*example/i,
      /\/\*\s*example/i,
      /#\s*example/i,
    ];
    
    return commentPatterns.some(p => p.test(content));
  }

  isDocumentation(filePath) {
    const docExtensions = ['.md', '.txt', '.rst', '.adoc'];
    const docFileNames = ['readme', 'changelog', 'contributing', 'license', 'todo'];
    
    const ext = filePath.split('.').pop();
    if (docExtensions.includes(`.${ext}`)) return true;
    
    const fileName = filePath.split(/[/\\]/).pop().toLowerCase();
    return docFileNames.some(name => fileName.includes(name));
  }

  shouldSuppressBasedOnContext(issue, context) {
    const suppressionRules = [
      {
        condition: context.isTestFile && this.isTestRelatedFinding(issue),
        reason: 'test file',
        suppress: true
      },
      {
        condition: context.isMockFile,
        reason: 'mock file',
        suppress: true
      },
      {
        condition: context.isGeneratedFile,
        reason: 'generated file',
        suppress: true
      },
      {
        condition: context.isExampleCode && this.isExpectedInExample(issue),
        reason: 'example code',
        suppress: true
      },
      {
        condition: context.isDocumentation,
        reason: 'documentation file',
        suppress: true
      },
    ];

    for (const rule of suppressionRules) {
      if (rule.condition) {
        return {
          shouldSuppress: rule.suppress,
          reason: rule.reason,
          context: {
            isTestFile: context.isTestFile,
            isMockFile: context.isMockFile,
            isGeneratedFile: context.isGeneratedFile,
            isExampleCode: context.isExampleCode,
            frameworks: context.frameworks,
          }
        };
      }
    }

    return { shouldSuppress: false, reason: null, context: null };
  }

  isTestRelatedFinding(issue) {
    const testRelatedRules = [
      'secrets',
      'hardcoded-password',
      'api-key',
      'token',
      'credential',
    ];

    const testSafeRules = [
      'xss',
      'sql-injection',
      'path-traversal',
      'command-injection',
    ];

    const issueType = (issue.type || '').toLowerCase();
    const issueRule = (issue.ruleId || '').toLowerCase();

    const isTestUnsafe = testRelatedRules.some(r => 
      issueType.includes(r) || issueRule.includes(r)
    );

    const isTestSafe = testSafeRules.some(r => 
      issueType.includes(r) || issueRule.includes(r)
    );

    return isTestUnsafe || !isTestSafe;
  }

  isExpectedInExample(issue) {
    const exampleSafeRules = [
      'todo',
      'comment',
      'console-log',
      'debugger',
      'unused',
    ];

    const issueRule = (issue.ruleId || '').toLowerCase();
    return exampleSafeRules.some(r => issueRule.includes(r));
  }

  checkTeamSuppression(issue) {
    const key = `${issue.file}:${issue.line}:${issue.ruleId}`;
    return this.teamSuppressions.has(key);
  }

  suppressIssue(issue, reason, suppressedBy = 'team') {
    const key = `${issue.file}:${issue.line}:${issue.ruleId}`;
    
    this.teamSuppressions.set(key, {
      file: issue.file,
      line: issue.line,
      ruleId: issue.ruleId,
      reason,
      suppressedBy,
      suppressedAt: new Date().toISOString(),
      teamAcknowledged: true,
    });

    return {
      success: true,
      suppression: this.teamSuppressions.get(key)
    };
  }

  filterIssuesWithContext(issues, _projectPath) {
    const filtered = [];
    const suppressed = [];

    for (const issue of issues) {
      const cacheKey = issue.file;
      
      let context = this.fileContextCache.get(cacheKey);
      if (!context) {
        context = this.analyzeFileContext(issue.file, issue.code || '');
        this.fileContextCache.set(cacheKey, context);
      }

      if (this.checkTeamSuppression(issue)) {
        suppressed.push({
          ...issue,
          suppressed: true,
          suppressionReason: 'team acknowledgment',
          suppressionSource: '.sentinel-suppressions.json'
        });
        continue;
      }

      const { shouldSuppress, reason, context: issueContext } = 
        this.shouldSuppressBasedOnContext(issue, context);

      if (shouldSuppress) {
        suppressed.push({
          ...issue,
          suppressed: true,
          suppressionReason: reason,
          contextAnalysis: issueContext
        });
      } else {
        filtered.push({
          ...issue,
          contextAnalysis: context.isLikelyFalsePositive ? 
            { likelyFalsePositive: true } : null
        });
      }
    }

    return {
      issues: filtered,
      suppressed,
      summary: {
        total: issues.length,
        active: filtered.length,
        suppressed: suppressed.length,
        suppressionRate: issues.length > 0 ? 
          (suppressed.length / issues.length * 100).toFixed(1) : 0,
        byReason: this.groupByReason(suppressed)
      }
    };
  }

  groupByReason(suppressedIssues) {
    return suppressedIssues.reduce((acc, issue) => {
      const reason = issue.suppressionReason || 'unknown';
      acc[reason] = (acc[reason] || 0) + 1;
      return acc;
    }, {});
  }

  async exportTeamSuppressions(outputPath) {
    const suppressions = Array.from(this.teamSuppressions.values());
    
    const exportData = {
      version: '1.0',
      exportedAt: new Date().toISOString(),
      suppressions
    };

    await fs.writeFile(outputPath, JSON.stringify(exportData, null, 2));
    return { success: true, count: suppressions.length };
  }

  clearCache() {
    this.fileContextCache.clear();
  }
}

export default ContextAwareSuppression;
