#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import chalk from 'chalk';

const HOOK_TEMPLATE = `#!/bin/sh
# Sentinel pre-push hook — blocks pushes with critical security issues
# Generated by: sentinel init-hooks
# Docs: https://github.com/KunjShah95/SENTINEL-CLI
#
# To bypass: git push --no-verify
# To disable: rm .git/hooks/pre-push

echo "🛡️  Sentinel: Running pre-push security check..."

# Run sentinel pre-commit anal ysis
SENTINEL_OUTPUT=$(sentinel pre-commit --format json 2>&1)
SENTINEL_EXIT=$?

if [ $SENTINEL_EXIT -ne 0 ]; then
  # Check if sentinel is available
  if echo "$SENTINEL_OUTPUT" | grep -q "command not found\|not found\|ENOENT"; then
    echo "⚠️  Sentinel CLI not found — skipping check. Install: npm install -g sentinel-cli"
    exit 0
  fi

  # Check for critical findings
  CRITICAL_COUNT=$(echo "$SENTINEL_OUTPUT" | grep -o '"critical"' | wc -l)
  if [ "$CRITICAL_COUNT" -gt 0 ]; then
    echo ""
    echo "❌  Blocking push: $CRITICAL_COUNT critical security issue(s) found."
    echo "   Fix them or use 'git push --no-verify' to bypass."
    echo ""
    echo "$SENTINEL_OUTPUT" | head -40
    exit 1
  fi

  echo "⚠️  Sentinel found issues (none critical) — push allowed."
fi

exit 0
`;

export async function runInitHooks({ hooks = ['pre-push'] } = {}) {
  const gitDir = join(process.cwd(), '.git');
  const hooksDir = join(gitDir, 'hooks');

  let gitDirStat;
  try {
    gitDirStat = await readFile(join(gitDir, 'HEAD'));
  } catch {
    console.error(chalk.red('✗ Not a git repository'));
    process.exit(1);
  }

  for (const hook of hooks) {
    const hookPath = join(hooksDir, hook);
    let existing = '';
    try {
      existing = await readFile(hookPath, 'utf8');
    } catch {}

    if (existing.includes('Sentinel')) {
      console.log(chalk.yellow(`⚠  ${hook} hook already contains Sentinel — skipping`));
      continue;
    }

    if (existing) {
      const backupPath = `${hookPath}.bak`;
      await writeFile(backupPath, existing, 'utf8');
      console.log(chalk.dim(`  Backed up existing hook to ${backupPath}`));
    }

    await writeFile(hookPath, HOOK_TEMPLATE, 'utf8');
    await import('node:fs').then(fs =>
      fs.chmodSync(hookPath, 0o755)
    );

    console.log(chalk.green(`✓ ${hook} hook installed`));
  }

  console.log(chalk.dim('\nTo bypass on next push: git push --no-verify'));
}
