import Link from "next/link";
import { Callout, CodeBlock } from "@/components/CodeBlock";
import { CompareTable, Cta, Faq, H2, H3, KeyTakeaways } from "@/components/Post";
import type { Post } from "@/lib/site";

export default {
  slug: "pr-owl-review-policy",
  title: "Deciding which pull requests are not worth reviewing",
  metaTitle: "PR Owl Part 4: What Not to Review",
  description:
    "The cheapest code in an AI reviewer and the part that decides your bill: drafts, forks, oversized diffs, generated files, and the ordering that makes every check cost nothing.",
  date: "2026-10-06",
  readingMinutes: 9,
  tags: ["Tutorial", "Cost", "Policy", "Code Review"],
  keyword: "ai code review cost control policy",
  series: { slug: "pr-owl-course", order: 4 },
  related: ["pr-owl-webhook-signature-verification", "reduce-llm-cost", "ai-coding-agent-guardrails"],
  faq: [
    {
      q: "Isn't a diff cap just going to skip reviews people want?",
      a: "Sometimes, and that is the correct trade. A 2,000-line diff is not something a model reviews well in any case; the finding rate falls off long before the cap. Where the cap does hurt is a large but legitimate refactor — a codemod, a dependency bump — and the honest answer is that those are exactly the pull requests where a human skim plus a linter beats a model.",
    },
    {
      q: "Should fork pull requests really be skipped by default?",
      a: "Yes, and not because they are untrustworthy in the sense of being wrong — because their head commit is attacker-controlled code that your infrastructure would touch. Part 8 is the whole argument. `forkPolicy: 'allow'` exists and reviews them read-only if you want that, but shipping it on is a decision about your risk appetite, not a default.",
    },
    {
      q: "Why does the order of the checks matter?",
      a: "Because some of them require work you have already paid for. The file list comes from the GitHub API and the diff cap can be computed from two integers in the webhook payload — so the cap runs first, and an oversized pull request is rejected before it costs an API call, let alone a model call. Every check is pure, and the expensive ones come last.",
    },
    {
      q: "How do I test this without a real pull request?",
      a: "It is pure functions over a plain object, which is why it is in its own module with no I/O. `decide()` takes a request and a policy and returns a decision; 29 tests in `pr-owl/__tests__/policy.test.ts` cover it with no network and no credentials. That is also the argument for keeping policy separate from the route — the layer worth testing hardest is the one with no side effects.",
    },
  ],
  body: () => (
    <>
      <KeyTakeaways>
        <p>
          Policy answers one question: <strong>should this pull request cost a model
          call?</strong> Everything it rejects is free, because a refusal is a pure
          function returning a string.
        </p>
        <p>
          Checks run cheapest-first. The diff cap is two integers already in the webhook
          payload, so an oversized pull request dies before an API call — let alone a
          model call.
        </p>
      </KeyTakeaways>

      <H2 id="problem" text="Why this is the part people skip" />
      <p>
        It is boring, it is pure, and it produces nothing visible. It is also the only
        code in the app that reliably makes it cheaper, and the only part that protects you
        from the day someone opens a 4,000-line pull request generated by a script and your
        reviewer spends four dollars and finds one typo.
      </p>
      <p>
        The reason it gets skipped is that it looks like configuration rather than code.
        It is code, it is the code with the best effort-to-value ratio in the app, and it
        belongs in its own module so the tests can hammer it without a network.
      </p>

      <H2 id="implementation" text="The decision function" />
      <CodeBlock
        label="pr-owl/lib/policy.ts"
        code={`export function decide(req: ReviewRequest, policy = DEFAULT_POLICY): Decision {
  if (policy.allowedRepos.length && !policy.allowedRepos.includes(req.repo)) {
    return { review: false, reason: \`\${req.repo} is not on the allow-list\` };
  }
  if (policy.ignoredAuthors.includes(req.author)) {
    return { review: false, reason: \`author \${req.author} is on the ignore list\` };
  }
  if (req.draft) {
    // Draft PRs are, by GitHub's own definition, not ready to be read closely.
    return { review: false, reason: 'draft pull request' };
  }

  const fork = isFromFork(req.baseRepo, req.headRepo);
  if (fork) {
    if (policy.forkPolicy === 'deny') {
      return { review: false, reason: 'pull request from a fork, and forkPolicy is deny' };
    }
    if (policy.forkPolicy === 'skip') {
      return { review: false, reason: 'pull request from a fork, and forkPolicy is skip' };
    }
  }

  if (exceedsDiffCap(req.additions, req.deletions, policy.maxDiffLines)) {
    // The cheapest way to bound spend: do not read the diff at all.
    return { review: false,
      reason: \`diff is \${req.additions + req.deletions} lines, over the \${policy.maxDiffLines}-line cap\` };
  }

  if (policy.ignoreGeneratedOnly && isGeneratedOnly(req.files)) {
    return { review: false, reason: 'every changed file is generated or a lockfile' };
  }

  return { review: true, readOnly: fork && policy.forkReadOnly, reason: ... };
}`}
      />
      <p>
        Note what the refusals return: a reason string, always. Not just{" "}
        <code className="font-mono text-[13px]">false</code>. When a developer opens a pull
        request and no review appears, the difference between &ldquo;the reviewer decided
        not to look&rdquo; and &ldquo;the reviewer is broken&rdquo; is the entire
        difference between five minutes and an afternoon — and a bare{" "}
        <code className="font-mono text-[13px]">false</code> gives you nothing to put in
        the log.
      </p>

      <H2 id="order" text="The ordering is the design" />
      <p>
        Every check is cheap, but not equally cheap, and two of them need data that costs
        something to obtain.
      </p>
      <CompareTable
        caption="Cost of each check, in the order decide() runs them"
        head={["Check", "Needs", "Cost if it fires"]}
        rows={[
          ["Repo allow-list", "nothing", "free — stops before any API call"],
          ["Ignored authors", "nothing", "free — stops before any API call"],
          ["Draft", "nothing", "free — stops before any API call"],
          ["Fork", "nothing", "free — the security decision"],
          ["Diff cap", "two ints in the payload", "free — the main cost control"],
          ["Generated only", "the file list", "one API call, already needed"],
          ["Review", "a clone and a model", "the expensive thing"],
        ]}
      />
      <p>
        The consequence is that the diff cap sits <em>above</em> the file-list check, so an
        oversized pull request is rejected without ever listing its files. Both
        <code className="font-mono text-[13px]">additions</code> and{" "}
        <code className="font-mono text-[13px]">deletions</code> arrive in the webhook
        payload, which is why this works before a single API call.
      </p>
      <Callout title="An ordering bug worth asserting">
        <p>
          With the default <code className="font-mono text-[13px]">forkPolicy: 'skip'</code>
          , a fork pull request never reaches the cap check — the fork branch returns
          first. That is correct, but it means{" "}
          <code className="font-mono text-[13px]">forkPolicy: 'allow'</code> silently changes
          what &ldquo;allow&rdquo; means: reviews fork pull requests of <em>any</em> size.
          There is a test asserting exactly that, because it is the kind of interaction
          that only shows up on someone else&rsquo;s repository.
        </p>
      </Callout>

      <H2 id="generated" text="Generated files, and a bug worth finding" />
      <p>
        A pull request that only touches{" "}
        <code className="font-mono text-[13px]">package-lock.json</code> is not a review,
        it is noise — and dependency bumps are common enough to matter.
      </p>
      <CodeBlock
        label="pr-owl/lib/policy.ts"
        code={`const GENERATED_PATTERNS = [
  /(^|\\/)package-lock\\.json$/,
  /(^|\\/)pnpm-lock\\.yaml$/,
  /(^|\\/)yarn\\.lock$/,
  /^dist\\//,
  /^build\\//,
  /^coverage\\//,
  /^__generated__\\//,
  /(^|\\/)[^/]*\\.min\\.(js|css)$/,
  /\\.snap$/,
  /^vendor\\//,
];`}
      />
      <p>
        Those directory patterns start with <code className="font-mono text-[13px]">^</code>{" "}
        and that is load-bearing. The first version was{" "}
        <code className="font-mono text-[13px]">/(^|\\/)dist\\//</code>, which matches{" "}
        <code className="font-mono text-[13px]">src/dist-helpers/x.js</code> — and more
        to the point, <code className="font-mono text-[13px]">src/build/config.js</code>. A
        source tree with a directory called{" "}
        <code className="font-mono text-[13px]">build</code> stopped being reviewed, and
        nothing anywhere reported a problem: the pull request simply had no comments on
        it.
      </p>
      <p>
        That is the failure mode this whole module is for. It is not that the reviewer
        crashes. It is that the reviewer quietly stops reviewing part of your codebase and
        everyone assumes there was nothing to say.
      </p>

      <H2 id="brief" text="The brief, and what is deliberately missing from it" />
      <p>
        What the agent actually receives. Two things are absent on purpose.
      </p>
      <CodeBlock
        label="pr-owl/lib/policy.ts"
        code={`export function buildBrief(req: ReviewRequest): string {
  return [
    \`Review pull request #\${req.prNumber} on \${req.repo}.\`,
    \`Title: \${req.title}\`,
    \`Author: \${req.author}\`,
    \`Head commit: \${req.headSha}\`,
    \`Changed files: \${req.files.length} (+\${req.additions} -\${req.deletions})\`,
    req.body?.trim() ? \`\\nDescription:\\n\${req.body.trim().slice(0, 2000)}\` : '',
    '',
    'The changed files are checked out in your working directory. Read them,',
    'and read whatever else you need for context — a change is rarely',
    'wrong on its own.',
    '',
    'Report only defects you can point at: a specific file, a specific',
    'line, and a specific reason it is wrong. If you are not confident',
    'something is a defect, leave it out. A review with three real',
    'findings is worth more than one with twenty speculative ones,',
    'because the cost of a false positive is that people stop reading.',
  ].filter(Boolean).join('\\n');
}`}
      />
      <ol className="list-decimal space-y-2.5 pl-5 text-muted marker:text-moss">
        <li>
          <strong className="text-paper">The diff is not in the prompt.</strong> It arrives
          as the working tree, so the agent reads it with tools. Embedding it as well would
          spend tokens on content it can fetch, and would put a large untrusted blob into
          the prompt where it competes for attention with the instructions.
        </li>
        <li>
          <strong className="text-paper">&ldquo;Be thorough&rdquo; is not in the prompt.</strong>{" "}
          That instruction is the single most reliable way to make a reviewer find more
          than is there. Asking for findings it can point at, and accepting that some will
          be missed, produces fewer comments and more of the ones you keep.
        </li>
        <li>
          <strong className="text-paper">The description is truncated to 2,000
          characters.</strong> A pull request body is attacker-controlled text on a public
          repository, and an unbounded one is a cheap way to spend your tokens.
        </li>
      </ol>
      <p>
        There is a test for the first one, because it is the kind of thing a later
        contributor adds &ldquo;just in case the checkout fails&rdquo; — and a reviewer that
        silently works from a stale inline diff is worse than one that fails.
      </p>

      <H2 id="testing" text="Testing a policy" />
      <p>
        The interesting assertions are the ones checking that something is{" "}
        <em>not</em> reviewed, because that is where an autonomous reviewer actually fails.
      </p>
      <CodeBlock
        label="__tests__/policy.test.ts"
        code={`it('still applies the cap to a fork PR that policy allows', () => {
  const skip = decide(req({ headRepo: 'stranger/api', additions: 5000 }));
  assert.equal(skip.review, false);
  assert.match(skip.reason, /fork/, 'the fork policy is evaluated first');

  const policy = { ...DEFAULT_POLICY, forkPolicy: 'allow' };
  const capped = decide(req({ headRepo: 'stranger/api', additions: 5000 }), policy);
  assert.equal(capped.review, false);
  assert.match(capped.reason, /cap/, 'the cap still applies once forks are allowed');
});

it('does not match a source directory that merely shares the name', () => {
  assert.equal(isGeneratedOnly([patch('src/build/config.js')]), false);
  assert.equal(isGeneratedOnly([patch('src/vendor/hand-written.js')]), false);
});`}
      />
      <p>
        And one that guards the fixtures themselves, which matters more than it looks: if
        the diff helper in the test file silently stopped producing a parseable patch, then
        every &ldquo;skips this file&rdquo; assertion would pass for the wrong reason.
      </p>

      <H2 id="faq" text="Frequently asked questions" />
      <Faq
        items={[
          {
            q: "Isn't a diff cap just going to skip reviews people want?",
            a: "Sometimes, and that is the correct trade. A 2,000-line diff is not something a model reviews well in any case; the finding rate falls off long before the cap. Where the cap does hurt is a large but legitimate refactor — a codemod, a dependency bump — and the honest answer is that those are exactly the pull requests where a human skim plus a linter beats a model.",
          },
          {
            q: "Should fork pull requests really be skipped by default?",
            a: "Yes, and not because they are untrustworthy in the sense of being wrong — because their head commit is attacker-controlled code that your infrastructure would touch. Part 8 is the whole argument. `forkPolicy: 'allow'` exists and reviews them read-only if you want that, but shipping it on is a decision about your risk appetite, not a default.",
          },
          {
            q: "Why does the order of the checks matter?",
            a: "Because some of them require work you have already paid for. The file list comes from the GitHub API and the diff cap can be computed from two integers in the webhook payload — so the cap runs first, and an oversized pull request is rejected before it costs an API call, let alone a model call. Every check is pure, and the expensive ones come last.",
          },
          {
            q: "How do I test this without a real pull request?",
            a: "It is pure functions over a plain object, which is why it is in its own module with no I/O. `decide()` takes a request and a policy and returns a decision; 29 tests in `pr-owl/__tests__/policy.test.ts` cover it with no network and no credentials. That is also the argument for keeping policy separate from the route — the layer worth testing hardest is the one with no side effects.",
          },
        ]}
      />

      <Cta
        title="Next: when to review it"
        body="Part 5 is the queue — bounded concurrency, and the coalescing rule that turns ten rebased branches into one review."
        href="/blog/pr-owl-review-queue"
        cta="Start part 5"
      />

      <p className="text-sm text-muted">
        The cost argument in more general form is in{" "}
        <Link href="/blog/reduce-llm-cost" className="text-moss underline-offset-4 hover:underline">
          reducing LLM cost
        </Link>
        , and why the refusals here are code rather than prompt text is the argument of{" "}
        <Link href="/blog/blast-radius-gate" className="text-moss underline-offset-4 hover:underline">
          the blast radius gate
        </Link>
        .
      </p>
    </>
  ),
} satisfies Post;
